### PR TITLE
Fix caching, decode images ahead of time 

### PR DESCRIPTION
**Pull request by actuday6418**

### CODE REVIEW

**Comment by actuday6418** [comment]
These commits implement the caching fix mentioned in #173 along with some miscellaneous improvements.

**Comment by TristanDebrunner** [comment]
Thanks @actuday6418. #173 also introduced #228, can you get that fixed as well in this PR?

**Comment by actuday6418** [comment]
Fixes #228

**Comment by TristanDebrunner** [comment]
Thanks for sending the updates. Unfortunately with the alphagen updates I think I need to test this on actual hardware to see how the keyer responds. I will not be able to do that until Friday or next Monday

**Comment by TristanDebrunner** [comment]
I also noticed one more problem while using the app at the tournament, #173 updated the sudden death view to be wide, but did not add the team name text back in. I have not had a chance to verify the behavior in the overtime periods. Could you fix this?

**Comment by TristanDebrunner** [comment]
I did some testing with the ATEM, and I don't think either the old code nor the new code you uploaded is correct.

Here is a screenshot of the old code:
old

And with the changes you made:
actuday

As you can see in both images, the white transparency is far less transparent than the black, though they should be equal. The changes proposed here make the problem worse, not better.

I did some research, and the ATEM is expecting a pre-multiplied key, which means we actually have to multiply the color channels by the alpha channel while processing from raw to color. I have tried changing to that, and I think the result is what we actually want:
pmk

I have pushed my changes [here](https://github.com/actuday6418/uwh-refbox-rs/pull/3). @actuday6418 could you make sure the pmk process also gets applied to any images that get downloaded?

**Comment by TristanDebrunner** [comment]
It doesn't look like #228 is resolved yet. See the video below.

https://github.com/AtlantisSports/uwh-refbox-rs/assets/6325217/2f6cd35d-5c20-49de-81c7-4e425484c097

**Comment by TristanDebrunner** [comment]
Also, the rendering when the game changes isn't quite fixed. Some comments on the video below:

1. It looks like we still have a 1-2 second freeze when the game number changes. I think this is acceptable, but it would be nice to reduce/eliminate
2. The change to the game number is rendered a few seconds before the team flags/names are updated. This needs to be fixed. If the new flags/names have not been processed by the backend yet, the placeholders must be used, not old data.

https://github.com/AtlantisSports/uwh-refbox-rs/assets/6325217/c0233d74-9260-4e60-8e73-3f4ca0ed737b

**Comment by actuday6418** [comment]
> It doesn't look like #228 is resolved yet. See the video below.
> timeout_flags_cropped.mp4

It was fixed with my change of drawing the timeout graphic underneath the team name banner graphic and drawing to the color feed without alpha. Looks like your change reintroduced the issue by adding transparency to the color feed, revealing the timeout graphics underneath.

I think the best solution, if possible, would be to switch the ATEM to straight keying. We would avoid the extra image processing as well.

If that cannot be done, I can try to come up with a solution like drawing only the part of the image that is on the right side of the time and state graphic.

**Comment by TristanDebrunner** [comment]
Unfortunately the pre-multiplied key is the only mode supported by the ATEM.

Would it be simple to just draw the flag first, then draw a black box over it on the left side? (Draw all the other stuff after the black box, so that nothing gets unintentionally covered)

**Pull request merged**
